# Generated by Django 3.2.7 on 2021-09-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=128)),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailCatalogue',
            fields=[
                ('order', models.BigIntegerField()),
                ('description', models.CharField(max_length=64)),
                ('id_detail_catalogue', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detail_catalogue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id_game_log', models.AutoField(primary_key=True, serialize=False)),
                ('id_tournament_fk', models.BigIntegerField()),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'db_table': 'game_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('identification', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('credits', models.BigIntegerField()),
                ('loginstate', models.BigIntegerField()),
            ],
            options={
                'db_table': 'gamer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterCatalogue',
            fields=[
                ('id_master_catalogue', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'master_catalogue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('num_credits', models.BigIntegerField()),
            ],
            options={
                'db_table': 'purchases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id_tournament', models.AutoField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('game_start', models.DateTimeField()),
                ('game_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'tournament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentSubject',
            fields=[
                ('id_tournament_subject', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tournament_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BigIntegerField()),
            ],
            options={
                'db_table': 'winner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamerTournament',
            fields=[
                ('id_gamer_fk', models.OneToOneField(db_column='id_gamer_fk', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pantalla.gamer')),
            ],
            options={
                'db_table': 'gamer_tournament',
                'managed': False,
            },
        ),
    ]
