# Generated by Django 3.1.13 on 2021-10-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantalla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dni',
            field=models.CharField(default='', max_length=64, null=True, unique=True),
        ),
    ]
